### ISSUE TITLE
Install Help Page Needed

### ISSUE THREAD

**Issue by ghost** [Dashing-io/smashing#16]
Hi,
Thanks for this fork.
Could you please add basic install help page for non ruby experts ?
`bundle install` seems still call original project (https://rubygems.org/gems/dashing).
Thx
T

**Comment by kinow** [comment]
Sure @TG-ATS 

Just installed dashing via bundle install this morning, and was planning on trying to install this new gem locally and write some docs.

**Comment by tylermauthe** [comment]
We need to publish the gem under a new name before any of this can realistically be changed.

`gem install dashing` will pull in the old gem until we update. That means that when you generate a dashboard, it will use the template from the old gem and the gemfile won't be updated to reference this fork either.

So, to get `bundle install` to install the fork, we need to publish it. To this end, I've created a poll to rename the gem here:

https://github.com/Dashing-io/dashing/issues/8#issuecomment-254685245

**Comment by tylermauthe** [comment]
You can now install this fork with `gem install smashing`. Thanks!

I've also updated the README as a stop-gap until we've created a proper homepage (#1).
