### ISSUE TITLE
Gem name

### ISSUE THREAD

**Issue by webmaster128** [Dashing-io/smashing#8]
I am just wondering, is it necessary to give the product a new name to get a new gem entry?

Or is it possible to silently ship updates of the old product from a new organization? Should that be done or should the user make an explicit decision about that?

Given that the original authors authorized the use of the name "dashing", maybe everything should be named dashing2 or something like this.

**Comment by iooner** [comment]
+1
Old gem maintained or new name ?

**Comment by VectreUK** [comment]
Maybe a new name. Reason behind this thought is it allows users to easily separate the original and fork. Might eliminate confusion?

Suggestion for the name: Truly Dashing (or something like this). Keeps the original name but is still unique and doesn't have any 2.0 as there's been no overhaul in code to justify a "new version".

Users then get the choice to remain with legacy Dashing or migrate to the fork. This way just seems a little more open to the users than silently migrating everyone.

**Comment by sjernigan** [comment]
I'd vote same gem name, new major version IF it's possible.  I suspect many users won't notice the difference especially if they're of the sort to upgrade without consulting the change log.  Going forward, having two gems out there will be confusing for new users.  BTW: I'm super happy about this new activity.

**Comment by tylermauthe** [comment]
My vote is dependant on what is to be done with this project.

At present, there are a number of issues:

- Batman.js is deprecated and should be replaced
  - There is a rich ecosystem of widgets that depend on Batman.js, so this is tricky.
- The web server (Thin) used for Dashing doesn't scale very well
- Related to both Batman.js and Thin, there are reports of memory leaks on both front-end and back-end in certain conditions
- The current architecture of the Server Sent Events endpoint doesn't scale very well 
  - All events for all dashboards are sent to all browsers, regardless of what dashboard you're viewing
- Dashing has dependencies on a JavaScript engine, this is not expressed in the Gemfile and causes installation issues on platforms that lack a native JS engine (most notably CentOS)
- `app.rb` should be rafactored to be a class so that it can be easily extended

If we are planning to fix all of these issues, then I'd say there are enough major changes to warrant a complete rename of the project.

If we're only going to tackle the problems above that will not cause breaking changes for users, then we may as well keep the name and brand identity. We can work with Shopify to complete that transition, including pushing a new version of the gem which replaces the old one.

**Comment by kinow** [comment]
>If we are planning to fix all of these issues, then I'd say there are enough major changes to warrant a complete rename of the project.

Agreed.

>If we're only going to tackle the problems above that will not cause breaking changes for users, then we may as well keep the name and brand identity. We can work with Shopify to complete that transition, including pushing a new version of the gem which replaces the old one.

Agreed as well.

I'd be +1 for a major release with the issues mentioned by @tylermauthe , +0 for a gem rename.

For me a major release could be enough, but would be fine with renaming the gem as well. @sjernigan and @VectreUK have good points pro/con the rename, but I don't have a strong opinion on this.

**Comment by webmaster128** [comment]
Maybe we should find out if we **can** reuse the old gem name before we discuss if we want to use it.

I never deployed a gem. Anyone?

**Comment by tylermauthe** [comment]
I've never deployed a gem to rubygems.org, but I've used custom ones of my own and the docs look really straight forward.

However, we will need to work with @pushmatrix / Shopify to get control of the gem in order to update it. If they aren't down with that, then we'd have to rename the project.

**Comment by christoff-1992** [comment]
Whats the best way to get Dashing up and running at the moment from this fork? also new to dashing but looks like exactly what I need. 

Great work on picking this up! .. glad I saw the comment linking to this on the Shopify GitHub.

**Comment by webmaster128** [comment]
@christoff-1992 thanks for your feedback and welcome! Could you please open a separate ticket specific for your question? I am sure it's easier for people to help out when there is a dedicated place to discuss this question.

**Comment by tyler-mauthe-hs** [comment]
I've reached out to @pushmatrix to see if we are even able to update the gem. If not, we'll have to rename it.

The more I think about it, the more I'd like to rename it so that we can start fresh... Thoughts?

**Comment by tyler-mauthe-hs** [comment]
Also, new name suggestion: **Smashing**

**Comment by howardsternisbatman** [comment]
I think a rename would be helpful for people just discovering the project...could save confusion in the long run.   I like Smashing as a name :)

**Comment by tylermauthe** [comment]
I haven't heard back from @pushmatrix but I think it's safe to assume that we've got to rename the project and publish a new gem.

Let's vote on a new name, add your reaction to vote for a new name:

😄  - `dashing_io`
🎉  - `smashing`
❤️  - `truly_dashing`

Voting closes on Friday - Midnight PT.

**Comment by kinow** [comment]
+1 for smashing :dagger:

**Comment by n-rodriguez** [comment]
+1 for smashing

**Comment by jeffko77** [comment]
🎉

**Comment by Austriker** [comment]
+1 smashing

**Comment by tylermauthe** [comment]
Okay, thanks to everyone who voted! I've renamed the gem Smashing and I've pushed it to RubyGems.

It worked for me, but before I close this issue I'd like someone else to confirm they can download and use the tool. Cheers!

**Comment by tylermauthe** [comment]
https://rubygems.org/gems/smashing

There are still lots of things that need to be done to move forward on this issue, I didn't rename any of the libs. At this point, the rename is purely cosmetic. However, I think the codebase is small enough that a true rename should be done -- after a proper refactoring and resolution of some of the issues I mentioned above is complete.

**Comment by kinow** [comment]
```
kinow@localhost:~$ cd /tmp
kinow@localhost:/tmp$ sudo gem install smashing
[sudo] password for kinow: 
Fetching: smashing-1.0.0.gem (100%)
Successfully installed smashing-1.0.0
Parsing documentation for smashing-1.0.0
Installing ri documentation for smashing-1.0.0
Done installing documentation for smashing after 0 seconds
1 gem installed
kinow@localhost:/tmp$ smashing new test
      create  test
      create  test/.gitignore
      create  test/Gemfile
      create  test/README.md
      create  test/assets/fonts/FontAwesome.otf
      create  test/assets/fonts/fontawesome-webfont.eot
      create  test/assets/fonts/fontawesome-webfont.svg
      create  test/assets/fonts/fontawesome-webfont.ttf
      create  test/assets/fonts/fontawesome-webfont.woff
      create  test/assets/fonts/fontawesome-webfont.woff2
      create  test/assets/images/logo.png
      create  test/assets/javascripts/application.coffee
      create  test/assets/javascripts/d3-3.2.8.js
      create  test/assets/javascripts/dashing.gridster.coffee
      create  test/assets/javascripts/gridster/jquery.gridster.min.js
      create  test/assets/javascripts/gridster/jquery.leanModal.min.js
      create  test/assets/javascripts/jquery.knob.js
      create  test/assets/javascripts/rickshaw-1.4.3.min.js
      create  test/assets/stylesheets/application.scss
      create  test/assets/stylesheets/font-awesome.css
      create  test/assets/stylesheets/jquery.gridster.min.css
      create  test/config.ru
      create  test/dashboards/layout.erb
      create  test/dashboards/sample.erb
      create  test/dashboards/sampletv.erb
      create  test/jobs/buzzwords.rb
      create  test/jobs/convergence.rb
      create  test/jobs/sample.rb
      create  test/jobs/twitter.rb
      create  test/lib
      create  test/public/404.html
      create  test/public/favicon.ico
      create  test/widgets/clock/clock.coffee
      create  test/widgets/clock/clock.html
      create  test/widgets/clock/clock.scss
      create  test/widgets/comments/comments.coffee
      create  test/widgets/comments/comments.html
      create  test/widgets/comments/comments.scss
      create  test/widgets/graph/graph.coffee
      create  test/widgets/graph/graph.html
      create  test/widgets/graph/graph.scss
      create  test/widgets/iframe/iframe.coffee
      create  test/widgets/iframe/iframe.html
      create  test/widgets/iframe/iframe.scss
      create  test/widgets/image/image.coffee
      create  test/widgets/image/image.html
      create  test/widgets/image/image.scss
      create  test/widgets/list/list.coffee
      create  test/widgets/list/list.html
      create  test/widgets/list/list.scss
      create  test/widgets/meter/meter.coffee
      create  test/widgets/meter/meter.html
      create  test/widgets/meter/meter.scss
      create  test/widgets/number/number.coffee
      create  test/widgets/number/number.html
      create  test/widgets/number/number.scss
      create  test/widgets/text/text.coffee
      create  test/widgets/text/text.html
      create  test/widgets/text/text.scss
```

**Comment by kinow** [comment]
And `smashing start` works as well. Thanks @tylermauthe !!!

**Comment by ZJvandeWeg** [comment]
Shouldn't this be closed?
